version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: idealista_postgres
    restart: always
    environment:
      POSTGRES_DB: realestate_db
      POSTGRES_USER: data_engineer
      POSTGRES_PASSWORD: secretpassword123
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
