CREATE SCHEMA IF NOT EXISTS real_estate;

DROP TABLE IF EXISTS real_estate.listings_export CASCADE;

CREATE TABLE real_estate.listings_export (
    website_name VARCHAR(50) DEFAULT 'idealista.pt',
    competence_date DATE NOT NULL,
    listing_id VARCHAR(50) PRIMARY KEY,
    listing_title TEXT NOT NULL,
    listing_description TEXT,
    property_type VARCHAR(50),
    listing_type VARCHAR(20) DEFAULT 'SALE',
    reference_market VARCHAR(20) DEFAULT 'RESIDENTIAL',
    country_code VARCHAR(3) DEFAULT 'PRT',
    location_description TEXT,
    location_region VARCHAR(100),
    location_province VARCHAR(100),
    location_city VARCHAR(100),
    location_zip VARCHAR(20),
    locaiton_neighborhood VARCHAR(100),
    location_street VARCHAR(150),
    location_street_n VARCHAR(20),
    location_lon VARCHAR(50),
    location_lat VARCHAR(50),
    area_unit VARCHAR(10) DEFAULT 'SQMT',
    area_value NUMERIC(12, 2),
    bedrooms INT,
    bathrooms INT,
    floor INT,
    total_floors INT,
    amenities_list TEXT,
    listing_date VARCHAR(20),
    listing_status VARCHAR(50) DEFAULT 'Available',
    agent_id VARCHAR(50),
    agent_url TEXT,
    currency_code VARCHAR(3) DEFAULT 'EUR',
    price NUMERIC(12, 2) NOT NULL,
    imageurl TEXT,
    itemurl TEXT NOT NULL
);